fix(pre-commit): Fix reuse hook failed due to `ModuleNotFoundError: No module named 'pkg_resources'`
This fixes the following error:

```
reuse....................................................................Failed
- hook id: reuse
- exit code: 1

Traceback (most recent call last):
  File "/home/brlin/.cache/pre-commit/repo5hyqakcs/py_env-python3/bin/reuse", line 5, in <module>
    from reuse._main import main
  File "/home/brlin/.cache/pre-commit/repo5hyqakcs/py_env-python3/lib/python3.12/site-packages/reuse/__init__.py", line 14, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
ModuleNotFoundError: No module named 'pkg_resources'
```

Signed-off-by: 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>